language: cpp
compiler:
  - gcc
env: BOOST_ROOT=/root/boost_1_67_0
install:
  - |
    wget http://prdownloads.sourceforge.net/libpng/zlib-1.2.11.tar.gz && \
    tar -xzf zlib-1.2.11.tar.gz && \
    cd zlib-1.2.11 && \
    CFLAGS=-m32 ./configure --static && \
    make && make install && \
    cd ..
  - |
    wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz && \
    tar -xzf boost_1_67_0.tar.gz
  - |
    cd boost_1_67_0 && \
    ./bootstrap.sh && \
    ./b2 link=static address-model=32 -sZLIB_SOURCE=/root/zlib-1.2.11 && \
    cd ..
before_script:
  - git submodule init
  - git submodule update
script:
  - make build-inside
